return {
	"uhm hello im a producer",
	"please dont ask me to make beats for you i dont like that",
	"Idk",
	"Oh yea",
	"Whatt",
	"Noooo",
	"That's not what the goat says (edited)",
	"You gotta be like",
	"\"Hi\"",
	"And then that's it",
	"Thanks",
	"Make me exp bot",
	"Brooooo",
	"😭😭😭😑",
	"Life bad",
	"Akira the goat is dead",
	"K",
}